# $Id: Makefile.djgpp,v 1.1.1.1 2020/05/16 02:37:00 rkiesling Exp $
#
# Makefile for DJGPP and GNU make.  No-ops because DJGPP
# does not install info and man pages in UNIX-ly locations.
#

CMD=cmd /C

all:


inst:


clean:
	$(CMD) del *~
	
