  LABEL,             METHODMSGLABEL,  /* 0. */
  LABEL,             OPENPAREN,       /* 1. */
  LABEL,             LABEL,           /* 2. */
  LABEL,             SEMICOLON,       /* 3. */
  METHODMSGLABEL,    LABEL,           /* 4. */
  METHODMSGLABEL,    CHAR,            /* 5. Overloaded C operators.  */
  METHODMSGLABEL,    EQ,              /* 6. */
  METHODMSGLABEL,    BOOLEAN_EQ,      /* 7. */
  METHODMSGLABEL,    GT,              /* 8. */
  METHODMSGLABEL,    GE,              /* 9. */
  METHODMSGLABEL,    ASR,             /* 10. */
  METHODMSGLABEL,    ASR_ASSIGN,      /* 11. */
  METHODMSGLABEL,    LT,              /* 12. */
  METHODMSGLABEL,    LE,              /* 13. */
  METHODMSGLABEL,    ASL,             /* 14. */
  METHODMSGLABEL,    ASL_ASSIGN,      /* 15. */
  METHODMSGLABEL,    PLUS,            /* 16. */
  METHODMSGLABEL,    PLUS_ASSIGN,     /* 17. */
  METHODMSGLABEL,    INCREMENT,       /* 18. */
  METHODMSGLABEL,    MINUS,           /* 19. */
  METHODMSGLABEL,    MINUS_ASSIGN,    /* 20. */
  METHODMSGLABEL,    DECREMENT,       /* 21. */
  METHODMSGLABEL,    DEREF,           /* 22. */
  METHODMSGLABEL,    MULT,            /* 23. */
  METHODMSGLABEL,    MULT_ASSIGN,     /* 24. */
  METHODMSGLABEL,    DIVIDE,          /* 25. */
  METHODMSGLABEL,    DIV_ASSIGN,      /* 26. */
  METHODMSGLABEL,    BIT_AND,         /* 27. */
  METHODMSGLABEL,    BOOLEAN_AND,     /* 28. */
  METHODMSGLABEL,    BIT_AND_ASSIGN,  /* 29. */
  METHODMSGLABEL,    BIT_COMP,        /* 30. */
  METHODMSGLABEL,    LOG_NEG,         /* 31. */
  METHODMSGLABEL,    INEQUALITY,      /* 32. */
  METHODMSGLABEL,    BIT_OR,          /* 33. */
  METHODMSGLABEL,    BIT_XOR,         /* 34. */
  METHODMSGLABEL,    BIT_OR_ASSIGN,   /* 35. */
  METHODMSGLABEL,    BIT_XOR_ASSIGN,  /* 36. */
  METHODMSGLABEL,    PERIOD,          /* 37. */
  METHODMSGLABEL,    ELLIPSIS,        /* 38. */
  METHODMSGLABEL,    LITERALIZE,      /* 39. */
  METHODMSGLABEL,    MACRO_CONCAT,    /* 40. */
  METHODMSGLABEL,    CONDITIONAL,     /* 41. */
  METHODMSGLABEL,    COLON,           /* 42. */
  METHODMSGLABEL,    BOOLEAN_AND,     /* 43. */
  METHODMSGLABEL,    BOOLEAN_OR,      /* 44. */
  METHODMSGLABEL,    MODULUS,         /* 45. */
  METHODMSGLABEL,    MODULUS_ASSIGN,  /* 46. */
  METHODMSGLABEL,    MATCH,           /* 47. */
  METHODMSGLABEL,    NOMATCH,         /* 48. */
  CHAR,              LABEL,           /* 49. */
  EQ,                LABEL,           /* 50. Overloaded operators. */
  BOOLEAN_EQ,     LABEL,           /* 51. */
  GT,             LABEL,           /* 52. */
  GE,             LABEL,           /* 53. */
  ASR,            LABEL,           /* 54. */
  ASR_ASSIGN,     LABEL,           /* 55. */
  LT,             LABEL,           /* 56. */
  LE,             LABEL,           /* 57. */
  ASL,            LABEL,           /* 58. */
  ASL_ASSIGN,     LABEL,           /* 59. */
  PLUS,           LABEL,           /* 60. */
  PLUS_ASSIGN,    LABEL,           /* 61. */
  INCREMENT,      LABEL,           /* 62. */
  MINUS,          LABEL,           /* 63. */
  MINUS_ASSIGN,   LABEL,           /* 64. */
  DECREMENT,      LABEL,           /* 65. */
  DEREF,          LABEL,           /* 66. */
  MULT,           LABEL,           /* 67. */
  MULT_ASSIGN,    LABEL,           /* 68. */
  DIVIDE,         LABEL,           /* 69. */
  DIV_ASSIGN,     LABEL,           /* 70. */
  BIT_AND,        LABEL,           /* 71. */
  BOOLEAN_AND,    LABEL,           /* 72. */
  BIT_AND_ASSIGN, LABEL,           /* 73. */
  BIT_COMP,       LABEL,           /* 74. */
  LOG_NEG,        LABEL,           /* 75. */
  INEQUALITY,     LABEL,           /* 76. */
  BIT_OR,         LABEL,           /* 77. */
  BIT_OR_ASSIGN,  LABEL,           /* 78. */
  BIT_XOR,        LABEL,           /* 79. */
  BIT_XOR_ASSIGN, LABEL,           /* 80. */
  PERIOD,         LABEL,           /* 81. */
  ELLIPSIS,       LABEL,           /* 82. */
  LITERALIZE,     LABEL,           /* 83. */
  MACRO_CONCAT,   LABEL,           /* 84. */
  CONDITIONAL,    LABEL,           /* 85. */
  COLON,          LABEL,           /* 86. */
  BOOLEAN_AND,    LABEL,           /* 87. */
  BOOLEAN_OR,     LABEL,           /* 88. */ 
  MODULUS,        LABEL,           /* 89. */ 
  MODULUS_ASSIGN, LABEL,           /* 90. */
  MATCH,          LABEL,           /* 91. */
  NOMATCH,        LABEL,           /* 92. */
