/* This is a machine generated file.  Please do not edit! */
char *__osx_i386_math_builtins[] = {
"__builtin_fabs",
"__builtin_fabsf",
"__builtin_fabsl",
"__builtin_huge",
"__builtin_inf",
"__builtin_inff",
"__builtin_infl",
"__builtin_isgreater",
"__builtin_isgreaterequal",
"__builtin_isless",
"__builtin_islessequal",
"__builtin_islessgreater",
"__builtin_isunordered",
"__builtin_nanf",
NULL, NULL };
char *__osx_i386_libkern_builtins[] = {
"OSReadSwapInt16",
"OSReadSwapInt32",
"OSReadSwapInt64",
"OSWriteSwapInt16",
"OSWriteSwapInt32",
"OSWriteSwapInt64",
"uint16_t",
"uint32_t",
"uint64_t",
"_OSSwapInt16",
"_OSSwapInt32",
"__uint16_t",
"__uint32_t",
NULL, NULL };
