/* This is a machine generated file.  Please do not edit! */
#include <stdio.h>
static char *gcc45_types[] = {
"__UINT_LEAST8_TYPE__", "unsigned char",
"__SIG_ATOMIC_TYPE__", "int",
"__UINTMAX_TYPE__", "long long unsigned int",
"__INT_FAST16_TYPE__", "int",
"__INT_FAST64_TYPE__", "long long int",
"__UINT8_TYPE__", "unsigned char",
"__INT_FAST32_TYPE__", "int",
"__UINT_LEAST16_TYPE__", "short unsigned int",
"__SIZE_TYPE__", "unsigned int",
"__INT8_TYPE__", "signed char",
"__INT_LEAST16_TYPE__", "short int",
"__UINT_LEAST64_TYPE__", "long long unsigned int",
"__UINT_FAST16_TYPE__", "unsigned int",
"__CHAR16_TYPE__", "short unsigned int",
"__INT_LEAST64_TYPE__", "long long int",
"__INT16_TYPE__", "short int",
"__INT_LEAST8_TYPE__", "signed char",
"__INTPTR_TYPE__", "int",
"__UINT16_TYPE__", "short unsigned int",
"__WCHAR_TYPE__", "long int",
"__UINT_FAST64_TYPE__", "long long unsigned int",
"__INT64_TYPE__", "long long int",
"__WINT_TYPE__", "unsigned int",
"__UINT_LEAST32_TYPE__", "unsigned int",
"__INT_LEAST32_TYPE__", "int",
"__UINT64_TYPE__", "long long unsigned int",
"__INT_FAST8_TYPE__", "signed char",
"__UINT_FAST32_TYPE__", "unsigned int",
"__CHAR32_TYPE__", "unsigned int",
"__INT32_TYPE__", "int",
"__INTMAX_TYPE__", "long long int",
"__PTRDIFF_TYPE__", "int",
"__UINT32_TYPE__", "unsigned int",
"__UINTPTR_TYPE__", "unsigned int",
"__UINT_FAST8_TYPE__", "unsigned char",
NULL, NULL,
};
